### ISSUE TITLE
ProcessManager print debug yields an error on print_debug

### ISSUE THREAD

**Issue by Skylion007** [popupcad/popupcad#7]
Here is the Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/skylion/Git/popupcad/dev_tools/process_manager.py", line 170
    print(*args,**kwargs)
          ^
SyntaxError: invalid syntax
```
>>>

**Comment by Skylion007** [comment]
Solved with commit
