### ISSUE TITLE
I can open file in windows but not in mac

### ISSUE THREAD

**Issue by zhiernteoh** [popupcad/popupcad#95]
There is error on the newest mac version where the second to last operation (laminate op) produces an error:
<class 'shapely.geos.TopologicalError'>: This operation could not be performed: Reason: unknown

This error does not occur on the windows version.

[device on SLL03.zip](https://github.com/popupcad/popupcad/files/192363/device.on.SLL03.zip)

**Comment by zhiernteoh** [comment]
here is the error stack:

```ERROR:shapely.geos:TopologyException: found non-noded intersection between LINESTRING (1083.22 6985.36, 1153.93 7056.07) and LINESTRING (1153.93 7056.07, 1260 6950) at 1153.9339828220131 7056.0660171779828
<class 'shapely.geos.TopologicalError'>: This operation could not be performed. Reason: unknown
Traceback (most recent call last):
  File "/Users/zhiernteoh/popupcad/popupcad/guis/editor.py", line 256, in open
    self.reprocessoperations()
  File "/Users/zhiernteoh/popupcad/popupcad/guis/editor.py", line 225, in reprocessoperations
    self.design.reprocessoperations(operations)
  File "/Users/zhiernteoh/popupcad/popupcad/filetypes/design.py", line 287, in reprocessoperations
    op.generate_outer1()
  File "/Users/zhiernteoh/popupcad/popupcad/filetypes/operation2.py", line 100, in generate_outer1
    self.generate(design)
  File "/Users/zhiernteoh/popupcad/popupcad/filetypes/operation2.py", line 103, in generate
    result = self.operate(design)
  File "/Users/zhiernteoh/popupcad/popupcad/manufacturing/laminateoperation2.py", line 134, in operate
    return laminate1.binaryoperation(laminate2, self.function)
  File "/Users/zhiernteoh/popupcad/popupcad/filetypes/laminate.py", line 107, in binaryoperation
    layerout = layer1.binaryoperation(layer2, function)
  File "/Users/zhiernteoh/popupcad/popupcad/filetypes/layer.py", line 65, in binaryoperation
    newgeom = function(operationgeom)
  File "/Users/zhiernteoh/anaconda/envs/popupcad_env/lib/python3.3/site-packages/shapely/geometry/base.py", line 559, in difference
    return geom_factory(self.impl['difference'](self, other))
  File "/Users/zhiernteoh/anaconda/envs/popupcad_env/lib/python3.3/site-packages/shapely/topology.py", line 70, in __call__
    self._check_topology(err, this, other)
  File "/Users/zhiernteoh/anaconda/envs/popupcad_env/lib/python3.3/site-packages/shapely/topology.py", line 39, in _check_topology
    raise err
shapely.geos.TopologicalError: This operation could not be performed. Reason: unknown```

**Comment by danaukes** [comment]
This is due to differences in the geometry engine, and is not within the
scope of popupCAD(99%).  Most likely you will have to twiddle any cleanup
operation values when moving between the two operating systems.

On Mon, Mar 28, 2016 at 12:43 PM, zhiernteoh <notifications@github.com>
wrote:

> here is the error stack:
>
> ERROR:shapely.geos:TopologyException: found non-noded intersection between
> LINESTRING (1083.22 6985.36, 1153.93 7056.07) and LINESTRING (1153.93
> 7056.07, 1260 6950) at 1153.9339828220131 7056.0660171779828
> <class 'shapely.geos.TopologicalError'>: This operation could not be
> performed. Reason: unknown
> Traceback (most recent call last):
> File "/Users/zhiernteoh/popupcad/popupcad/guis/editor.py", line 256, in
> open
> self.reprocessoperations()
> File "/Users/zhiernteoh/popupcad/popupcad/guis/editor.py", line 225, in
> reprocessoperations
> self.design.reprocessoperations(operations)
> File "/Users/zhiernteoh/popupcad/popupcad/filetypes/design.py", line 287,
> in reprocessoperations
> op.generate_outer1()
> File "/Users/zhiernteoh/popupcad/popupcad/filetypes/operation2.py", line
> 100, in generate_outer1
> self.generate(design)
> File "/Users/zhiernteoh/popupcad/popupcad/filetypes/operation2.py", line
> 103, in generate
> result = self.operate(design)
> File
> "/Users/zhiernteoh/popupcad/popupcad/manufacturing/laminateoperation2.py",
> line 134, in operate
> return laminate1.binaryoperation(laminate2, self.function)
> File "/Users/zhiernteoh/popupcad/popupcad/filetypes/laminate.py", line
> 107, in binaryoperation
> layerout = layer1.binaryoperation(layer2, function)
> File "/Users/zhiernteoh/popupcad/popupcad/filetypes/layer.py", line 65, in
> binaryoperation
> newgeom = function(operationgeom)
> File
> "/Users/zhiernteoh/anaconda/envs/popupcad_env/lib/python3.3/site-packages/shapely/geometry/base.py",
> line 559, in difference
> return geom_factory(self.impl['difference'](self, other))
> File
> "/Users/zhiernteoh/anaconda/envs/popupcad_env/lib/python3.3/site-packages/shapely/topology.py",
> line 70, in __call__
> self._check_topology(err, this, other)
> File
> "/Users/zhiernteoh/anaconda/envs/popupcad_env/lib/python3.3/site-packages/shapely/topology.py",
> line 39, in _check_topology
> raise err
> shapely.geos.TopologicalError: This operation could not be performed.
> Reason: unknown
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/95#issuecomment-202552734>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University

**Comment by nickgravish** [comment]
Strange though because I can open the file with no error on my mac. Interesting.

**Comment by danaukes** [comment]
The windows installer is good because if you keep your version updated, it
will act consistently across all installs.  The mac version depends on when
you installed your particular python packages and can thus get out of
date.  I would recommend updating your python packages.

Right now I am not actively testing on mac.

On Mon, Mar 28, 2016 at 1:07 PM, Nick Gravish <notifications@github.com>
wrote:

> Strange though because I can open the file with no error on my mac.
> Interesting.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/95#issuecomment-202561971>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University
